name: Deploy

on: [push]
    # paths:
      # - "RELEASE"

jobs:
  build:
    # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Read version
        id: read_version
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: RELEASE
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tizot
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # - 
      #   name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: false
      #     tags: 
      #       tizot/cine:${{ steps.read_version.outputs.content }}
      #       tizot/cine:latest
      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
      #
      #
